### ISSUE TITLE
从json resume 的网站上拿的json sample 不能被import

### ISSUE THREAD

**Issue by mave99a** [blocklet/json-resume#1]
从这里获取的demo json：https://jsonresume.org/schema/

**Comment by frmachao** [comment]
https://jsonresume.org/schema/ 这段 json 本身格式有问题，前端需要将格式错误的信息展示出来。
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/22849231/163781007-d21f7229-3138-4c00-81ef-870517b3f423.png">

**Comment by frmachao** [comment]
fix : https://test.registry.arcblock.io/blocklets/z8ia2tqQWfL5wJyhf1oPovrQXTkUMGmXd63Gd
